project_id = "jajkfzwzmogpkwzclisv"

[functions.image-generation]
verify_jwt = false

[functions.improve-proxy]
verify_jwt = false

[functions.briefing-proxy]
verify_jwt = false

[functions.pdf-transcription-proxy]
verify_jwt = false

