
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jajkfzwzmogpkwzclisv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imphamtmend6bW9ncGt3emNsaXN2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2OTY4ODksImV4cCI6MjA2MjI3Mjg4OX0.1iDX0yqCmE28tocq6zfkt7_v5b4vv_A_H0rqBRnvxHI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'implicit',
  }
});

// Debug utility to check auth state
export const checkAuthStatus = async () => {
  try {
    const { data, error } = await supabase.auth.getSession();
    
    if (error) {
      console.error('Error checking auth status:', error);
      return null;
    }
    
    return {
      session: data.session,
      user: data.session?.user ?? null
    };
  } catch (e) {
    console.error('Exception checking auth status:', e);
    return null;
  }
};
